// Re-exports the root branding config.
// The _branding files are generated by the prebuild script from config/branding.ts.
// Run `npm run prebuild` after editing config/branding.ts (dev script does this automatically).
export { branding } from './_branding.js';
export type { BrandingConfig } from './_branding.types.js';
