// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/features": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/auth/logout": {
    params: {};
  };
  "/auth/forgot-password": {
    params: {};
  };
  "/auth/reset-password": {
    params: {};
  };
  "/auth/change-password": {
    params: {};
  };
  "/checkout": {
    params: {};
  };
  "/checkout/success": {
    params: {};
  };
  "/checkout/cancel": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/profile": {
    params: {};
  };
  "/dashboard/membership": {
    params: {};
  };
  "/dashboard/usage": {
    params: {};
  };
  "/dashboard/billing": {
    params: {};
  };
  "/test": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/tiers": {
    params: {};
  };
  "/admin/features": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/pricing" | "/contact" | "/features" | "/auth/login" | "/auth/register" | "/auth/logout" | "/auth/forgot-password" | "/auth/reset-password" | "/auth/change-password" | "/checkout" | "/checkout/success" | "/checkout/cancel" | "/dashboard" | "/dashboard/profile" | "/dashboard/membership" | "/dashboard/usage" | "/dashboard/billing" | "/test" | "/admin" | "/admin/tiers" | "/admin/features" | "/admin/users";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/" | "/pricing" | "/contact" | "/features" | "/auth/login" | "/auth/register" | "/auth/logout" | "/auth/forgot-password" | "/auth/reset-password" | "/auth/change-password" | "/checkout" | "/checkout/success" | "/checkout/cancel";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/pricing.tsx": {
    id: "routes/pricing";
    page: "/pricing";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/features.tsx": {
    id: "routes/features";
    page: "/features";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.register.tsx": {
    id: "routes/auth.register";
    page: "/auth/register";
  };
  "routes/auth.logout.tsx": {
    id: "routes/auth.logout";
    page: "/auth/logout";
  };
  "routes/auth.forgot-password.tsx": {
    id: "routes/auth.forgot-password";
    page: "/auth/forgot-password";
  };
  "routes/auth.reset-password.tsx": {
    id: "routes/auth.reset-password";
    page: "/auth/reset-password";
  };
  "routes/auth.change-password.tsx": {
    id: "routes/auth.change-password";
    page: "/auth/change-password";
  };
  "routes/checkout._index.tsx": {
    id: "routes/checkout._index";
    page: "/checkout";
  };
  "routes/checkout.success.tsx": {
    id: "routes/checkout.success";
    page: "/checkout/success";
  };
  "routes/checkout.cancel.tsx": {
    id: "routes/checkout.cancel";
    page: "/checkout/cancel";
  };
  "routes/_protected.tsx": {
    id: "routes/_protected";
    page: "/dashboard" | "/dashboard/profile" | "/dashboard/membership" | "/dashboard/usage" | "/dashboard/billing" | "/test" | "/admin" | "/admin/tiers" | "/admin/features" | "/admin/users";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard" | "/dashboard/profile" | "/dashboard/membership" | "/dashboard/usage" | "/dashboard/billing";
  };
  "routes/dashboard._index.tsx": {
    id: "routes/dashboard._index";
    page: "/dashboard";
  };
  "routes/dashboard.profile.tsx": {
    id: "routes/dashboard.profile";
    page: "/dashboard/profile";
  };
  "routes/dashboard.membership.tsx": {
    id: "routes/dashboard.membership";
    page: "/dashboard/membership";
  };
  "routes/dashboard.usage.tsx": {
    id: "routes/dashboard.usage";
    page: "/dashboard/usage";
  };
  "routes/dashboard.billing.tsx": {
    id: "routes/dashboard.billing";
    page: "/dashboard/billing";
  };
  "routes/test.tsx": {
    id: "routes/test";
    page: "/test";
  };
  "routes/test._index.tsx": {
    id: "routes/test._index";
    page: "/test";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin" | "/admin/tiers" | "/admin/features" | "/admin/users";
  };
  "routes/admin._index.tsx": {
    id: "routes/admin._index";
    page: "/admin";
  };
  "routes/admin.tiers.tsx": {
    id: "routes/admin.tiers";
    page: "/admin/tiers";
  };
  "routes/admin.features.tsx": {
    id: "routes/admin.features";
    page: "/admin/features";
  };
  "routes/admin.users.tsx": {
    id: "routes/admin.users";
    page: "/admin/users";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_layout": typeof import("./app/routes/_layout.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/pricing": typeof import("./app/routes/pricing.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/features": typeof import("./app/routes/features.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/auth.register": typeof import("./app/routes/auth.register.tsx");
  "routes/auth.logout": typeof import("./app/routes/auth.logout.tsx");
  "routes/auth.forgot-password": typeof import("./app/routes/auth.forgot-password.tsx");
  "routes/auth.reset-password": typeof import("./app/routes/auth.reset-password.tsx");
  "routes/auth.change-password": typeof import("./app/routes/auth.change-password.tsx");
  "routes/checkout._index": typeof import("./app/routes/checkout._index.tsx");
  "routes/checkout.success": typeof import("./app/routes/checkout.success.tsx");
  "routes/checkout.cancel": typeof import("./app/routes/checkout.cancel.tsx");
  "routes/_protected": typeof import("./app/routes/_protected.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/dashboard._index": typeof import("./app/routes/dashboard._index.tsx");
  "routes/dashboard.profile": typeof import("./app/routes/dashboard.profile.tsx");
  "routes/dashboard.membership": typeof import("./app/routes/dashboard.membership.tsx");
  "routes/dashboard.usage": typeof import("./app/routes/dashboard.usage.tsx");
  "routes/dashboard.billing": typeof import("./app/routes/dashboard.billing.tsx");
  "routes/test": typeof import("./app/routes/test.tsx");
  "routes/test._index": typeof import("./app/routes/test._index.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/admin._index": typeof import("./app/routes/admin._index.tsx");
  "routes/admin.tiers": typeof import("./app/routes/admin.tiers.tsx");
  "routes/admin.features": typeof import("./app/routes/admin.features.tsx");
  "routes/admin.users": typeof import("./app/routes/admin.users.tsx");
};